# tomcat
server:
  port: 9000
  # 项目contextPath，一般在正式发布版本中，我们不配置
  servlet:
    context-path: /
spring:
  application:
      name: kitty-generator
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://120.79.210.194:3306/generator?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
      username: root
      password: zz123456
  thymeleaf:
    mode: HTML5
    encoding: utf-8
    cache: false
    suffix: .html
    servlet:
      content-type: text/html
    prefix: classpath:/static/

beetl:
  templatesPath: templates
